{% set name = "pydatamail" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydatamail-{{ version }}.tar.gz
  sha256: 4be682fda77c49ab17f06297572320c1e33e8e1b6ca32e821b6f42d48e1ee27d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.5.2
    - numpy >=1.22.4
    - pandas >=1.4.2
    - python >=3.6
    - sqlalchemy >=1.4.37
    - tqdm >=4.64.0
    - scikit-learn >=1.1.1

test:
  imports:
    - pydatamail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyscioffice/pydatamail
  summary: pydatamail - a python module to apply data science principles to email processing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
