{% set name = "pydatamail" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydatamail-{{ version }}.tar.gz
  sha256: 1712aaa4cd8ccc0d189d5b25f1d0a9d9d0998d6b0762491bea351e46fef30423

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.5.2
    - numpy >=1.23.0
    - pandas >=1.4.3
    - python >=3.6
    - sqlalchemy >=1.4.39
    - tqdm >=4.64.0

test:
  imports:
    - pydatamail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyscioffice/pydatamail
  summary: pydatamail - a python module to apply data science principles to email processing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
