{% set name = "pydatamail" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydatamail-{{ version }}.tar.gz
  sha256: 1c0d872ea953f4e92caaceae6458adcf85558c0138d06cb617d22fe859708395

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.5.1
    - numpy >=1.22.2
    - pandas >=1.4.1
    - python >=3.6
    - sqlalchemy >=1.4.31
    - tqdm >=4.62.3
    - scikit-learn >=1.0.2

test:
  imports:
    - pydatamail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyscioffice/pydatamail
  summary: pydatamail - a python module to apply data science principles to email processing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
